### ISSUE TITLE
Working on Own Object detection. (ex:Smurf Counting) ModuleNotFoundError: No module named 'nets'

### ISSUE THREAD

**Issue by samareshyadav55** [ahmetozlu/tensorflow_object_counting_api#65]

**Comment by bidyutchanda** [comment]
Check out this issue. 

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/150

The problem is 'nets' is actually a folder created by OP and not a Python package. And if Python does not find that folder in the given path, this error is raised.
